# Generated by Django 3.0.5 on 2021-02-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210207_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='memo',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
